config/routes.rb
Rails.application.routes.draw do
  

devise_for :users
resources :posts
resources :comments
root "posts#index"

get "profile/:id" => "users#show"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
	has_many :posts
	has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		user = current_user
		comment = Comment.new(comment_params)
		comment.post_id = params[:post_id]
		comment.user_id = user.id
		if comment.save
			redirect_to "/posts/#{params[:post_id]}"
		else
			render 	"/posts/#{params[:post_id]}"
		end
	end


	def show
		@comment = Comment.find(params[:id])
	end

	def edit
		@comment = Comment.find(params[:id])
	end

	def update
		@comment = Comment.find(params[:id])
		@comment.user_id = current_user.id
		if @comment.update(comment_params)
			redirect_to "/"
		else 
			render "/comments/#{@comment.id}/edit"
		end
	end

	def destroy
		@comment = Comment.find(params[:id])
		@comment.destroy
		redirect_to "/"
	end

	private

	def comment_params
		params.require(:comment).permit(:content, :user_id, :post_id)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!
	def index
		@posts = Post.all
	end

	def new
		@post = Post.new
	end

	def create
		post = Post.new(post_params)
		post.user_id = current_user.id
		if(post.save)
			redirect_to "/posts"
		else
			render "/posts/new"
		end	
	end

	def show
		@comment = Comment.new
		@post = Post.find(params[:id])
		

	end	

	def edit 
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])
		@post.user_id = current_user.id
		if @post.update(post_params)
			redirect_to "/"
		else 
			render "/posts/#{@post.id}/edit"
		end
	end


	def destroy 
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to "/"
	end






	private
	def post_params
		params.require(:post).permit(:title, :content, :user_id)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
  	@user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/edit.html.erb
<h2>Edit comment</h2>

<%= form_for @comment do |f| %>
Content for edit: <%= f.text_field :content %>
<%= f.submit %>
<% end %>

<%= link_to "Destroy comment", comment_path(@comment), method: :delete %>

app/views/comments/show.html.erb
Thsi is the show page!!!!

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <nav>
    <% if !user_signed_in? %>
      <li><a href="/users/sign_up">Sign up</a></li>
      <li><a href="/users/sign_in">Log in</a></li>
    <% end %> 
     <% if user_signed_in? %>
     <li><a href="/posts">Home</a></li>
     <li><a href="/posts/new">Create a new Blog</a></li>
     <li><%=link_to "Log out", destroy_user_session_path,
                                              method: :delete %>
     </li>
     <div class='current-user'><li><a href="/profile/<%=current_user.id %>"><%= current_user.email %></a></li></div>

     <% end %>
  </nav>

  <body>
    <%= yield %>
    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p> 
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
Title: <%= f.text_field :title %>
Content: <%= f.text_field :content %>
<%= f.submit  %>



<% end %>

app/views/posts/edit.html.erb
<h3>Edit Post form:</h3>
<%= link_to "Destroy Post", post_path, method: :delete %>

<%= render "form" %>

app/views/posts/index.html.erb
<h1 style='text-align: center; margin-top: 60px'>Welcome to my Blogs!!!</h1>


	<% @posts.each do |p| %>
	<div class='index-posts'>
		<div><b>Title:</b> <a href="/posts/<%=p.id %>"><%= p.title %></a></div>
		<div><i>Content:</i> <%= p.content %></div>
		<div><b>Author:</b> <%= p.user.email %></div>
		<br>
			<div class='index-comments'>
				<% p.comments.limit(5).each_with_index do |c, index| %>
					<div><%= index + 1 %>	Content: <%= c.content %></div>
					<div>User: <%= c.user.email %></div>
				<% end %>
			</div>
	</div>
	<% end %>

app/views/posts/new.html.erb
<h3>Create a new Post:</h3>

<%= render "form" %>

app/views/posts/show.html.erb
<h2>Post</h2>

<% if current_user.id == @post.user.id %>
	<div>Title:<a href='/posts/<%=@post.id %>/edit'>	<%= @post.title%></a></div>
<% end %>

<div>Content: <%= @post.content %></div>
<div>author: <a href="/profile/<%= current_user.id %>"><%= @post.user.email %></a></div>





<h3>Comment on this Post: </h3>

<%= form_for @comment do |f| %>
	<%= f.text_area :content %>
	<%= hidden_field_tag :post_id, @post.id %>
	<%= f.submit %>
<% end %>

<div class='comments'>
	Comments: <% @post.comments.each do |p| %>
		<div><a href="/comments/<%= p.id %>/edit"> <%= p.content %></a> | <%= p.user.email %></div>

			<% end %>
</div>

app/views/users/show.html.erb
<h3>Profile Page</h3>


	<div class='user-name'>	<%= @user.email %></div>
	<div class='edit-form'>
		<% if current_user.id == @user.id %>
			<a href='/users/edit'>Edit</a>
		<% end %>
	</div>

<h3>List of all Blogs of this user: </h3>
<div class='blog-list'>
	<% @user.posts.each_with_index do |b, index| %>
		<div><%= index + 1 %></div>
		<div>Title: <%= b.title %></div>
		<div>Content: <%= b.content %></div>
		<div>Date: <%= b.created_at.to_date %></div>
		<br>
	<% end %>
</div>